name: final_ui
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2022090601

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:

  flutter:
    sdk: flutter
  pin_code_fields: ^7.4.0
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_screenutil: ^5.5.3+2
  dots_indicator: ^2.1.0
  page_view_indicators: ^2.0.0
  bottom_navy_bar: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user.png
    - assets/].png
    - assets/flag.png
    - assets/Gmail.png
    - assets/Facebook.png
    - assets/Google.png
    - assets/Rectangle.png
    - assets/Group.png
    - assets/offer.png
    - assets/map.png
    - assets/fastfood.png
    - assets/splash.png
    -  assets/ad.png
    - assets/Search.png
    - assets/Notification.png
    - assets/Group.png
    - assets/shop.png
    - assets/wecon.png
    - assets/dp.png
    - assets/mosque.png
    - assets/map.png
    - assets/offer.png
    - assets/news.png
    - assets/compass.png
    - assets/discount.png
    - assets/home.png
    - assets/menu.png
    - assets/user_s.png
    - assets/offer_banner.png
    - assets/act_group.png
    - assets/loading.png



  fonts:
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #     style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Quantico
      fonts:
        - asset: fonts/Quantico-Regular.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
