name: final_ui
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:

  flutter:
    sdk: flutter
  pin_code_fields: ^7.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user.png
    - assets/].png
    - assets/flag.png
    - assets/Gmail.png
    - assets/Facebook.png
    - assets/Google.png



  fonts:
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #     style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
